# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

desc "Build the given scheme"
lane :build do |options|
    
    increment_build_number(
      build_number: number_of_commits
    )

    build_app(
      scheme: options[:scheme],
      clean: true,
      output_directory: "./build"
    )

    upload_to_testflight(
      team_id: options[:apple_team_id],
    )

end
